Repository chirp-community/chirp-community, pull requests merged in 2023-06, with the labels that each got.

#179 #174-게시판 기능 추가 구현
  frontend/src/ComponentsBoard/ArticleHeader/index.js
  frontend/src/ComponentsBoard/ArticlePage/index.js
  frontend/src/ComponentsBoard/BoardPage/index.js
  frontend/src/ComponentsBoard/Comment/index.js
Labels: enhancement

#180 #177 - 홈페이지 대략적 구조 잡기
  frontend/src/ComponentsBoard/MainPage/BoardListCom.js
  frontend/src/ComponentsBoard/MainPage/CardWithThumbnail.js
  frontend/src/ComponentsBoard/MainPage/IconTable.js
  frontend/src/ComponentsBoard/MainPage/RandomLikeArticle.js
  frontend/src/ComponentsBoard/MainPage/RecentLikeArticle.js
  frontend/src/ComponentsBoard/MainPage/RecentLikeComment.js
  frontend/src/ComponentsBoard/MainPage/RecentListCom.js
  frontend/src/ComponentsBoard/MainPage/RisingLikeArticle.js
  frontend/src/ComponentsBoard/MainPage/RisingViewArticle.js
  frontend/src/ComponentsBoard/MainPage/index.js
  frontend/src/ComponentsUtils/List/ListWithPageBar.js
  frontend/src/ComponentsUtils/index.js
Labels: documentation, enhancement

#182 #177 - 홈페이지 대략적 구조 잡기
  frontend/src/ComponentsBoard/MainPage/RecentLikeArticle.js
  frontend/src/ComponentsBoard/MainPage/RecentLikeComment.js
  frontend/src/ComponentsBoard/MainPage/RecentListCom.js
  frontend/src/ComponentsBoard/MainPage/RisingLikeArticle.js
  frontend/src/ComponentsBoard/MainPage/RisingViewArticle.js
  frontend/src/ComponentsBoard/MainPage/index.js
Labels: documentation, enhancement

#187 Feature/#181 추천급상승 게시판구현
  back_end/src/main/java/com/chirp/community/controller/ArticleController.java
  back_end/src/main/java/com/chirp/community/entity/projection/ArticleMapperWithNumLikes.java
  back_end/src/main/java/com/chirp/community/model/ArticleDto.java
  back_end/src/main/java/com/chirp/community/model/response/ArticleReadBestLikesResponse.java
  back_end/src/main/java/com/chirp/community/repository/ArticleRepository.java
  back_end/src/main/java/com/chirp/community/service/ArticleService.java
  back_end/src/main/java/com/chirp/community/service/ArticleServiceImpl.java
  back_end/src/main/resources/data.sql
  back_end/src/test/java/com/chirp/community/repository/ArticleRepositoryTest.java
  frontend/src/ComponentsBoard/ArticleCreatePage/indxe.js
  frontend/src/ComponentsBoard/MainPage/BoardListComBestLikes.js
  frontend/src/ComponentsBoard/MainPage/RisingLikeArticle.js
Labels: enhancement

#186 #185 - 주간 최고 조회수 게시물 조회 api 구현
  back_end/src/main/java/com/chirp/community/controller/ArticleController.java
  back_end/src/main/java/com/chirp/community/repository/ArticleRepository.java
  back_end/src/main/java/com/chirp/community/service/ArticleService.java
  back_end/src/main/java/com/chirp/community/service/ArticleServiceImpl.java
  frontend/src/ComponentsBoard/MainPage/BoardListComBestViews.js
  frontend/src/ComponentsBoard/MainPage/RisingViewArticle.js
Labels: documentation, enhancement

#184 #183 - 랜덤 게시판 목록 api 구현 및 최근 댓글 게시글 조회 api 구현
  back_end/src/main/java/com/chirp/community/controller/ArticleCommentController.java
  back_end/src/main/java/com/chirp/community/controller/ArticleController.java
  back_end/src/main/java/com/chirp/community/controller/BoardController.java
  back_end/src/main/java/com/chirp/community/model/response/ArticleCommentReadRecentlyResponse.java
  back_end/src/main/java/com/chirp/community/model/response/ArticleReadRecentlyResponse.java
  back_end/src/main/java/com/chirp/community/repository/BoardRepository.java
  back_end/src/main/java/com/chirp/community/service/ArticleCommentService.java
  back_end/src/main/java/com/chirp/community/service/ArticleCommentServiceImpl.java
  back_end/src/main/java/com/chirp/community/service/ArticleService.java
  back_end/src/main/java/com/chirp/community/service/ArticleServiceImpl.java
  back_end/src/main/java/com/chirp/community/service/BoardService.java
  back_end/src/main/java/com/chirp/community/service/BoardServiceImpl.java
  frontend/src/ComponentsBoard/MainPage/RecentListCom.js
Labels: documentation, enhancement

#189 #188 - 추천 급상승 게시판 구현
  frontend/src/ComponentsBoard/MainPage/RisingLikeArticle.js
  frontend/src/ComponentsBoard/MainPage/RisingViewArticle.js
Labels: bug

#193 #192-게시글작성 버그수정
  frontend/src/ComponentsBoard/ArticleCreatePage/indxe.js
Labels: enhancement

#194 #191 - API 명세서 작성
  back_end/build.gradle
  back_end/src/main/java/com/chirp/community/configuration/SwaggerConfig.java
  back_end/src/main/java/com/chirp/community/controller/ArticleCommentController.java
  back_end/src/main/java/com/chirp/community/controller/ArticleCommentDocs.java
  back_end/src/main/java/com/chirp/community/controller/ArticleController.java
  back_end/src/main/java/com/chirp/community/controller/ArticleDocs.java
  back_end/src/main/java/com/chirp/community/controller/AuthController.java
  back_end/src/main/java/com/chirp/community/controller/AuthDocs.java
  back_end/src/main/java/com/chirp/community/controller/BoardController.java
  back_end/src/main/java/com/chirp/community/controller/BoardDocs.java
  back_end/src/main/java/com/chirp/community/controller/SiteUserController.java
  back_end/src/main/java/com/chirp/community/controller/SiteUserDocs.java
  back_end/src/main/java/com/chirp/community/model/request/ArticleCommentCreateRequest.java
  back_end/src/main/java/com/chirp/community/model/request/ArticleCommentUpdateRequest.java
  back_end/src/main/java/com/chirp/community/model/request/ArticleCreateRequest.java
  back_end/src/main/java/com/chirp/community/model/request/ArticleUpdateRequest.java
  back_end/src/main/java/com/chirp/community/model/request/AuthRequest.java
  back_end/src/main/java/com/chirp/community/model/request/BoardCreateRequest.java
  back_end/src/main/java/com/chirp/community/model/request/BoardUpdateRequest.java
  back_end/src/main/java/com/chirp/community/model/request/SiteUserCreateRequest.java
  back_end/src/main/java/com/chirp/community/model/request/SiteUserUpdateRequest.java
  back_end/src/main/java/com/chirp/community/model/response/ArticleCommentReadRecentlyResponse.java
  back_end/src/main/java/com/chirp/community/model/response/ArticleCommentReadResponse.java
  back_end/src/main/java/com/chirp/community/model/response/ArticleReadBestLikesResponse.java
  back_end/src/main/java/com/chirp/community/model/response/ArticleReadBoardPageRowResponse.java
  back_end/src/main/java/com/chirp/community/model/response/ArticleReadMyPageRowResponse.java
  back_end/src/main/java/com/chirp/community/model/response/ArticleReadRecentlyResponse.java
  back_end/src/main/java/com/chirp/community/model/response/ArticleReadResponse.java
  back_end/src/main/java/com/chirp/community/model/response/AuthReadResponse.java
  back_end/src/main/java/com/chirp/community/model/response/BoardReadResponse.java
  back_end/src/main/java/com/chirp/community/model/response/ErrorResponse.java
  back_end/src/main/java/com/chirp/community/model/response/LikesReadResponse.java
  back_end/src/main/java/com/chirp/community/model/response/SiteUserReadResponse.java
  back_end/src/main/java/com/chirp/community/model/response/SiteUserReadRowResponse.java
  back_end/src/main/java/com/chirp/community/utils/ParameterOfPageableForSwagger.java
Labels: documentation, enhancement

#196 #195 - 최근 작성한 댓글 목록 버그 수정
  back_end/src/main/java/com/chirp/community/model/response/ArticleCommentReadRecentlyResponse.java
  frontend/src/ComponentsBoard/MainPage/RecentLikeComment.js
Labels: bug

#198 #197 - Web Server 도커 이미지 빌드
  frontend/Dockerfile
  frontend/ForDockerfile/nginx.conf
Labels: documentation, enhancement

#200 #199-백엔드 도커파일 생성 및 이미지 생성, 동작 확인
  back_end/Dockerfile
Labels: enhancement

#202 #201 - 서버 구성을 위한 Docker-Compose 설정
  back_end/docker-compose.yml
  frontend/ForDockerfile/nginx.conf
  frontend/src/utils/index.js
Labels: enhancement

#205 #204 - 필요없는 docker-compose.yml 제거
  back_end/docker-compose.yml
Labels: documentation

#207 #206 - 배포 자동화 설정
  .github/workflows/build-push-docker.yml
Labels: documentation, enhancement

#208 #206 - 배포 자동화 설정
  .github/workflows/build-push-docker.yml
Labels: bug

#209 #206 - 배포 자동화 설정
  .github/workflows/build-push-docker.yml
Labels: bug

#210 #206 - 배포 자동화 설정
  .github/workflows/build-push-docker.yml
Labels: bug

#211 #206 - 배포 자동화 설정
  .github/workflows/build-push-docker.yml
  .gitignore
  back_end/.gitignore
  back_end/gradlew
  back_end/gradlew.bat
Labels: bug

#212 #206 - 배포 자동화 설정
  .github/workflows/build-push-docker.yml
Labels: bug

#215 #214 - 운영서버를 위한 flyway 설정
  .github/workflows/build-push-docker.yml
  back_end/Dockerfile
  back_end/build.gradle
  back_end/src/main/resources/application-h2db.yml
  back_end/src/main/resources/application-mysql.yml
  back_end/src/main/resources/application-redis-local.yml
  back_end/src/main/resources/application-redis-prod.yml
  back_end/src/main/resources/application.yml
  back_end/src/main/resources/db/migration/mysql/V1__init_schema.sql
  back_end/src/main/resources/db/migration/mysql/V2__init_data.sql
Labels: documentation, enhancement

#216 #206 - 배포 자동화 설정
  .github/workflows/build-push-docker.yml
Labels: bug

#217 #206 - 배포 자동화 설정
  .github/workflows/build-push-docker.yml
  back_end/gradlew
  back_end/gradlew.bat
Labels: bug

#218 #206 - 배포 자동화 설정
  .github/workflows/build-push-docker.yml
Labels: bug

#219 Feature/#175 각 api 성능 측정
  back_end/.gitignore
  back_end/build.gradle
  back_end/src/main/java/com/chirp/community/CommunityApplication.java
  back_end/src/main/java/com/chirp/community/aspect/LoggingAspect.java
  back_end/src/main/java/com/chirp/community/configuration/AuthenticationConfig.java
  back_end/src/main/java/com/chirp/community/configuration/filter/HttpRequestSessionIdRepositoryFilter.java
  back_end/src/main/java/com/chirp/community/configuration/filter/LoggingFilter.java
  back_end/src/main/java/com/chirp/community/configuration/filter/PageSessionIdRepositoryFilter.java
  back_end/src/main/java/com/chirp/community/configuration/filter/SessionIdRepositoryFilter.java
  back_end/src/main/java/com/chirp/community/utils/LogUtils.java
  back_end/src/main/java/com/chirp/community/utils/SessionIdLogUtils.java
  back_end/src/main/resources/application-jpa.yml
  back_end/src/main/resources/application-security.yml
  back_end/src/main/resources/application.yml
  back_end/src/main/resources/logback-jpa.xml
  back_end/src/main/resources/logback-log.xml
  back_end/src/main/resources/logback-security.xml
  back_end/src/main/resources/logback-spring.xml
  frontend/src/api/index.js
  frontend/src/routes/RouteProxy.js
  frontend/src/routes/index.js
  frontend/src/utils/index.js
Labels: documentation, enhancement

#225 #224 - 공개키를 발급하는 API 구현
  back_end/.gitignore
  back_end/src/main/java/com/chirp/community/configuration/AsymmetricKeyConfig.java
  back_end/src/main/java/com/chirp/community/controller/AuthController.java
  back_end/src/main/java/com/chirp/community/controller/AuthDocs.java
  back_end/src/main/java/com/chirp/community/model/response/KeyReadResponse.java
  back_end/src/main/java/com/chirp/community/properties/JwtProperties.java
  back_end/src/main/resources/application-jwt.yml
  back_end/src/main/resources/mock.application-emailsecurity.yml
  back_end/src/main/resources/mock.application-jwt.yml
Labels: bug

#226 #223 - JWT payload 관련 설정 코드 리펙토링
  back_end/src/main/java/com/chirp/community/configuration/JwtConfig.java
  back_end/src/main/java/com/chirp/community/service/AuthServiceImpl.java
  back_end/src/main/java/com/chirp/community/utils/JwtTokenWithRS256Utils.java
Labels: bug

#227 #222 - 누락된 cascade 추가
  back_end/src/main/java/com/chirp/community/entity/Article.java
  back_end/src/main/java/com/chirp/community/entity/ArticleComment.java
  back_end/src/main/resources/db/migration/mysql/V1__init_schema.sql
Labels: bug

#233 #232 - 분리된 profile에 대한 이메일 설정
  back_end/src/main/java/com/chirp/community/properties/VerificationCodeProperties.java
  back_end/src/main/java/com/chirp/community/service/AuthServiceImpl.java
  back_end/src/main/java/com/chirp/community/utils/EmailContentUtils.java
  back_end/src/main/resources/application-email-local.yml
  back_end/src/main/resources/application-email-prod.yml
  back_end/src/main/resources/application.yml
Labels: bug

#230 #90 - csrf 보안 잠정 중단
  back_end/src/main/java/com/chirp/community/configuration/AuthenticationConfig.java
  back_end/src/main/java/com/chirp/community/configuration/CsrfConfig.java
  frontend/src/api/index.js
Labels: bug

#229 #228 - React 프로젝트 환경변수 분리
  frontend/.env.development
  frontend/.env.production
  frontend/package-lock.json
  frontend/package.json
  frontend/src/utils/index.js
Labels: bug

#231 Feature/#221 페이지 바 기능을 위한 count query 작성
  back_end/src/main/java/com/chirp/community/repository/ArticleRepository.java
Labels: bug

#236 #235 - 로고 이미지 및 불필요한 기능 삭제
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/src/ComponentsBoard/MainPage/index.js
  frontend/src/Header/index.js
Labels: bug
