Repository chirp-community/chirp-community, pull requests merged in 2023-05, with the labels that each got.

#3 merge feature/#2_백엔드_프로젝트_구현 to main
  back_end/.gitignore
  back_end/build.gradle
  back_end/gradlew
  back_end/gradlew.bat
  back_end/settings.gradle
  back_end/src/main/java/com/chirp/community/CommunityApplication.java
  back_end/src/main/resources/application.properties
  back_end/src/test/java/com/chirp/community/CommunityApplicationTests.java
Labels: documentation, enhancement

#8 #7 - 현 상황에서의 설정 파일 분리
  back_end/src/main/resources/application-datasource.yml
  back_end/src/main/resources/application-h2db.yml
  back_end/src/main/resources/application-jpa.yml
  back_end/src/main/resources/application-mysql.yml
  back_end/src/main/resources/application-server.yml
  back_end/src/main/resources/application.properties
  back_end/src/main/resources/application.yml
Labels: documentation, enhancement

#9 Feature/#4 게시판 도메인 설계 및 base entity 설계
  back_end/src/main/java/com/chirp/community/entity/BaseEntity.java
  back_end/src/main/java/com/chirp/community/entity/Board.java
  back_end/src/main/resources/mysql_schema.sql
Labels: documentation, enhancement

#10 #6 - site_user 도메인 설계
  back_end/src/main/java/com/chirp/community/entity/SiteUser.java
  back_end/src/main/java/com/chirp/community/type/RoleType.java
  back_end/src/main/resources/mysql_schema.sql
Labels: documentation, enhancement

#13 #12 - BoardController 생성 및 DTO 생성
  back_end/src/main/java/com/chirp/community/controller/BoardController.java
  back_end/src/main/java/com/chirp/community/model/BoardDto.java
  back_end/src/main/java/com/chirp/community/model/request/BoardCreateRequest.java
  back_end/src/main/java/com/chirp/community/model/request/BoardUpdateRequest.java
  back_end/src/main/java/com/chirp/community/model/response/BoardReadResponse.java
  back_end/src/main/java/com/chirp/community/service/BoardService.java
Labels: documentation, enhancement

#15 #14 - BoardService 및 BoardRepository 생성
  back_end/src/main/java/com/chirp/community/exception/CommunityException.java
  back_end/src/main/java/com/chirp/community/repository/BoardRepository.java
  back_end/src/main/java/com/chirp/community/service/BoardServiceImpl.java
Labels: documentation, enhancement

#17 #16 - 일괄 오류 처리의 필요성.
  back_end/src/main/java/com/chirp/community/exception/ExceptionHandlerController.java
Labels: documentation, enhancement

#20 #18 - SiteUserController 및 DTO 구현
  back_end/src/main/java/com/chirp/community/controller/SiteUserController.java
  back_end/src/main/java/com/chirp/community/model/SiteUserDto.java
  back_end/src/main/java/com/chirp/community/model/request/SiteUserCreateRequest.java
  back_end/src/main/java/com/chirp/community/model/request/SiteUserUpdateRequest.java
  back_end/src/main/java/com/chirp/community/model/response/SiteUserReadResponse.java
  back_end/src/main/java/com/chirp/community/service/SiteUserService.java
Labels: enhancement

#22 #21 - SiteUserService 및 SiteUserRepository 구현
  back_end/build.gradle
  back_end/src/main/java/com/chirp/community/entity/SiteUser.java
  back_end/src/main/java/com/chirp/community/exception/ExceptionHandlerController.java
  back_end/src/main/java/com/chirp/community/repository/SiteUserRepository.java
  back_end/src/main/java/com/chirp/community/service/SiteUserServiceImpl.java
  back_end/src/main/java/com/chirp/community/utils/ConvertRequestToMap.java
  back_end/src/test/java/com/chirp/community/exception/ExceptionHandlerControllerTest.java
  back_end/src/test/java/com/chirp/community/repository/SiteUserRepositoryTest.java
  back_end/src/test/java/com/chirp/community/utils/SetProfile.java
Labels: documentation, enhancement

#33 Feature/#32 spring security 설정
  back_end/build.gradle
  back_end/src/main/java/com/chirp/community/configuration/AsymmetricKeyConfig.java
  back_end/src/main/java/com/chirp/community/configuration/AuthenticationConfig.java
  back_end/src/main/java/com/chirp/community/configuration/CorsConfig.java
  back_end/src/main/java/com/chirp/community/configuration/PasswordEncodeConfig.java
  back_end/src/main/java/com/chirp/community/configuration/filter/JwtFilter.java
  back_end/src/main/java/com/chirp/community/exception/CommunityAccessDeniedHandler.java
  back_end/src/main/java/com/chirp/community/exception/CommunityAuthenticationEntryPoint.java
  back_end/src/main/java/com/chirp/community/model/SiteUserDto.java
  back_end/src/main/java/com/chirp/community/properties/CorsProperties.java
  back_end/src/main/java/com/chirp/community/properties/JwtProperties.java
  back_end/src/main/java/com/chirp/community/repository/SiteUserRepository.java
  back_end/src/main/java/com/chirp/community/service/SiteUserService.java
  back_end/src/main/java/com/chirp/community/service/SiteUserServiceImpl.java
  back_end/src/main/java/com/chirp/community/type/RoleType.java
  back_end/src/main/java/com/chirp/community/utils/JwtFilterUtils.java
  back_end/src/main/java/com/chirp/community/utils/JwtTokenWithRS256Utils.java
  back_end/src/main/resources/application-cors.yml
  back_end/src/main/resources/application-jwt.yml
  back_end/src/main/resources/application.yml
Labels: documentation, enhancement

#35 #34 - Jpa Auditing 기능 구현
  back_end/src/main/java/com/chirp/community/configuration/JpaAuditingConfig.java
  back_end/src/main/java/com/chirp/community/entity/Board.java
  back_end/src/main/java/com/chirp/community/entity/SiteUser.java
Labels: documentation, enhancement

#37 #34 - 도메인 별 DB Index 추가
  back_end/src/main/java/com/chirp/community/entity/Board.java
  back_end/src/main/java/com/chirp/community/entity/SiteUser.java
Labels: documentation, enhancement

#39 #38 - SiterUser 도메인 update 기능 디버깅
  back_end/src/main/java/com/chirp/community/service/BoardServiceImpl.java
  back_end/src/main/java/com/chirp/community/service/SiteUserServiceImpl.java
Labels: bug, documentation

#41 Feature/#24 article 도메인 관련 api 구현
  back_end/src/main/java/com/chirp/community/controller/ArticleController.java
  back_end/src/main/java/com/chirp/community/controller/BoardController.java
  back_end/src/main/java/com/chirp/community/controller/SiteUserController.java
  back_end/src/main/java/com/chirp/community/entity/Article.java
  back_end/src/main/java/com/chirp/community/model/ArticleDto.java
  back_end/src/main/java/com/chirp/community/model/request/ArticleCreateRequest.java
  back_end/src/main/java/com/chirp/community/model/request/ArticleUpdateRequest.java
  back_end/src/main/java/com/chirp/community/model/response/ArticleReadResponse.java
  back_end/src/main/java/com/chirp/community/model/response/ArticleReadRowResponse.java
  back_end/src/main/java/com/chirp/community/model/response/SiteUserReadRowResponse.java
  back_end/src/main/java/com/chirp/community/repository/ArticleRepository.java
  back_end/src/main/java/com/chirp/community/service/ArticleService.java
  back_end/src/main/java/com/chirp/community/service/ArticleServiceImpl.java
Labels: bug, documentation, enhancement

#43 #42 - MySQL schema.sql 작성 최신화 및 버그 수정
  back_end/src/main/resources/application-mysql.yml
  back_end/src/main/resources/mysql_schema.sql
Labels: bug, documentation, enhancement

#46 #45 - JwtFilter 적용 안한 버그 수정
  back_end/src/main/java/com/chirp/community/configuration/AuthenticationConfig.java
Labels: bug

#48 #47 - h2 console을 사용하기 위한 추가 설정
  back_end/src/main/java/com/chirp/community/configuration/AuthenticationConfig.java
Labels: bug

#50 #49 - hdata.sql 적용 불가 문제 해결
  back_end/src/main/resources/application-h2db.yml
Labels: bug

#52 #51 - site_user 도메인 초기화 버그
  back_end/src/main/java/com/chirp/community/entity/SiteUser.java
Labels: bug

#54 #53 - @CreatedDate 가 작동하지 않는 버그
  back_end/src/main/java/com/chirp/community/CommunityApplication.java
Labels: bug

#55 #53 - @CreatedDate 가 작동하지 않는 버그
  back_end/src/main/java/com/chirp/community/configuration/JpaAuditingConfig.java
Labels: bug

#56 #44-프론트엔드 프로젝트구성
  frontend/.gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
Labels: enhancement

#58 #57-gitignore 추가
  frontend/.gitignore
Labels: enhancement

#65 #64 - Cors Origin 결정
  back_end/src/main/java/com/chirp/community/configuration/CorsConfig.java
  back_end/src/main/resources/application-cors.yml
Labels: bug

#67 #66 - SiteUser의 role 칼럼의 Convert 문제 해결
  back_end/src/main/java/com/chirp/community/entity/SiteUser.java
Labels: bug

#69 #68 - 로그인 시 토큰을 발급해주는 API 구현
  back_end/src/main/java/com/chirp/community/controller/AuthController.java
  back_end/src/main/java/com/chirp/community/model/request/AuthRequest.java
  back_end/src/main/java/com/chirp/community/model/response/AuthReadResponse.java
  back_end/src/main/java/com/chirp/community/service/AuthService.java
  back_end/src/main/java/com/chirp/community/service/AuthServiceImpl.java
Labels: documentation, enhancement

#71 #70 - jpaAuditing 설정 버그 수정
  back_end/src/main/java/com/chirp/community/configuration/JpaAuditingConfig.java
  back_end/src/main/java/com/chirp/community/model/SiteUserDto.java
Labels: bug

#73 #72 - 에러 응답 전송 시 Json 형식으로 전송
  back_end/src/main/java/com/chirp/community/exception/CommunityAccessDeniedHandler.java
  back_end/src/main/java/com/chirp/community/exception/CommunityAuthenticationEntryPoint.java
  back_end/src/main/java/com/chirp/community/exception/ExceptionHandlerController.java
  back_end/src/main/java/com/chirp/community/model/response/ErrorResponse.java
Labels: enhancement

#77 Feature/#76 프론트 파일 구조 결정
  frontend/src/App.js
  frontend/src/ComponentsUsers/Footer/css.css
  frontend/src/ComponentsUsers/Footer/index.js
  frontend/src/ComponentsUsers/Header/css.css
  frontend/src/ComponentsUsers/Header/index.js
  frontend/src/ComponentsUsers/Login/css.css
  frontend/src/ComponentsUsers/Mock/css.css
  frontend/src/ComponentsUsers/index.js
  frontend/src/api/index.js
  frontend/src/routes/index.js
  frontend/src/utils/index.js
Labels: documentation, enhancement

#79 #78 - BoardController.readAllByKeyword 파라미터인 keyword의 초기값 지정
  back_end/src/main/java/com/chirp/community/controller/BoardController.java
Labels: bug

#81 #80 - 누락된 bootstrap 적용 수정
  frontend/src/App.js
  frontend/src/components/Footer/css.css
  frontend/src/components/Footer/index.js
  frontend/src/components/Header/css.css
  frontend/src/components/Header/index.js
  frontend/src/components/Login/css.css
  frontend/src/components/Login/index.js
  frontend/src/components/Mock/css.css
  frontend/src/components/Mock/index.js
  frontend/src/components/index.js
Labels: bug

#83 #82 - header 컴포넌트 수정
  frontend/src/ComponentsUsers/Header/css.css
  frontend/src/ComponentsUsers/Header/index.js
Labels: bug

#86 #84 - 로그인 페이지 구현
  frontend/src/ComponentsUsers/Login/css.css
  frontend/src/ComponentsUsers/Login/index.js
Labels: documentation, enhancement

#88 #87 - 회원 가입 페이지 생성
  back_end/src/main/java/com/chirp/community/service/SiteUserServiceImpl.java
  back_end/src/main/java/com/chirp/community/utils/CheckTools.java
  frontend/src/ComponentsUsers/SignUp/css.css
  frontend/src/ComponentsUsers/SignUp/index.js
  frontend/src/ComponentsUsers/index.js
  frontend/src/routes/index.js
Labels: documentation, enhancement

#91 #90 - csrf 보안 잠정 중단
  back_end/src/main/java/com/chirp/community/configuration/AuthenticationConfig.java
Labels: documentation

#92 #59-프론트엔드 파일구조 변경
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Header/css.css
  frontend/src/Header/index.js
  frontend/src/routes/index.js
Labels: enhancement

#95 #94 - ExceptionHandlerController 버그 수정
  back_end/src/main/java/com/chirp/community/exception/ExceptionHandlerController.java
Labels: bug

#99 #98 - JWT claim 내용 추가
  back_end/src/main/java/com/chirp/community/configuration/JwtConfig.java
  back_end/src/main/java/com/chirp/community/service/AuthServiceImpl.java
  back_end/src/main/java/com/chirp/community/type/RoleType.java
  back_end/src/main/java/com/chirp/community/utils/ConvertToJwtClaims.java
  back_end/src/main/java/com/chirp/community/utils/JwtTokenWithRS256Utils.java
Labels: documentation, enhancement

#101 #100 - Sheet 컴포넌트 추가
  frontend/src/ComponentsUsers/Sheet/css.css
  frontend/src/ComponentsUsers/Sheet/index.js
Labels: documentation, enhancement

#103 #102 - RNW 컴포넌트 생성
  frontend/src/ComponentsUsers/RNW/css.css
  frontend/src/ComponentsUsers/RNW/index.js
Labels: documentation, enhancement

#106 Feature/#93 게시판페이지 기본틀 구현
  back_end/.gitignore
  back_end/gradlew
  back_end/gradlew.bat
  back_end/src/main/resources/data.sql
  frontend/package-lock.json
  frontend/package.json
  frontend/src/ComponentsBoard/Board/Board.css
  frontend/src/ComponentsBoard/Board/Board.js
  frontend/src/ComponentsBoard/Main/index.css
  frontend/src/ComponentsBoard/Main/index.js
  frontend/src/ComponentsBoard/index.js
  frontend/src/routes/index.js
Labels: enhancement

#108 #107 - 각종 유용한 utility 함수들 추가
  frontend/src/utils/index.js
Labels: documentation, enhancement

#111 #110 - 기존 컴포넌트들 리펙토링
  frontend/src/ComponentsUsers/Header/index.js
  frontend/src/ComponentsUsers/Mock/css.css
  frontend/src/ComponentsUsers/RNW/index.js
  frontend/src/ComponentsUsers/Sheet/index.js
  frontend/src/ComponentsUsers/index.js
Labels: bug

#113 Feature/#112 게시판페이지 기본구현
  back_end/src/main/resources/data.sql
  frontend/src/ComponentsBoard/Board/Board.css
  frontend/src/ComponentsBoard/Board/Board.js
  frontend/src/ComponentsBoard/Board/index.css
  frontend/src/ComponentsBoard/Board/index.js
  frontend/src/ComponentsBoard/Main/index.js
  frontend/src/ComponentsBoard/index.js
  frontend/src/Header/index.js
  frontend/src/routes/index.js
Labels: enhancement

#116 #114-게시판 기본 기능 및 기초적인 구조 구현
  frontend/src/ComponentsBoard/Article/index.css
  frontend/src/ComponentsBoard/Article/index.js
  frontend/src/ComponentsBoard/Board/index.js
  frontend/src/ComponentsBoard/index.js
  frontend/src/routes/index.js
Labels: enhancement

#124 #123 - 잘못된 CascadeType 교정
  back_end/src/main/java/com/chirp/community/entity/Article.java
  back_end/src/main/java/com/chirp/community/entity/Board.java
  back_end/src/main/java/com/chirp/community/entity/SiteUser.java
Labels: bug

#126 #125 - src/api/index.js 내용 보완
  frontend/src/ComponentsUsers/Login/index.js
  frontend/src/ComponentsUsers/SignUp/index.js
  frontend/src/api/index.js
Labels: bug, documentation, enhancement

#128 #127 - 테스트를 위한 예시 데이터 적재
  back_end/src/main/resources/data.sql
Labels: documentation, enhancement

#132 Feature/#89 유저 개인 페이지 생성
  back_end/src/main/java/com/chirp/community/configuration/AuthenticationConfig.java
  back_end/src/main/java/com/chirp/community/configuration/JpaAuditingConfig.java
  back_end/src/main/java/com/chirp/community/controller/SiteUserController.java
  back_end/src/main/java/com/chirp/community/repository/ArticleRepository.java
  back_end/src/main/java/com/chirp/community/service/ArticleService.java
  back_end/src/main/java/com/chirp/community/service/ArticleServiceImpl.java
  back_end/src/main/java/com/chirp/community/service/SiteUserService.java
  back_end/src/main/java/com/chirp/community/service/SiteUserServiceImpl.java
  back_end/src/main/java/com/chirp/community/utils/AccessAuthorizer.java
  frontend/public/401-Unauthorized-t.jpg
  frontend/src/ComponentsUsers/MyPage/ArticleList.js
  frontend/src/ComponentsUsers/MyPage/CommentList.js
  frontend/src/ComponentsUsers/MyPage/Info.js
  frontend/src/ComponentsUsers/MyPage/List.js
  frontend/src/ComponentsUsers/MyPage/ListCom.js
  frontend/src/ComponentsUsers/MyPage/PaginationBar.js
  frontend/src/ComponentsUsers/MyPage/Profile.js
  frontend/src/ComponentsUsers/MyPage/SearchInput.js
  frontend/src/ComponentsUsers/MyPage/TitleWithIcon.js
  frontend/src/ComponentsUsers/MyPage/css.css
  frontend/src/ComponentsUsers/MyPage/index.js
  frontend/src/ComponentsUsers/index.js
  frontend/src/routes/index.js
Labels: documentation, enhancement

#133 #117-게시판 내용 추가 및 컴포넌트화
  frontend/src/ComponentsBoard/Article/index.js
  frontend/src/ComponentsBoard/ArticleHeader/index.css
  frontend/src/ComponentsBoard/ArticleHeader/index.js
  frontend/src/ComponentsBoard/ArticlePage/index.css
  frontend/src/ComponentsBoard/ArticlePage/index.js
  frontend/src/ComponentsBoard/Board/index.js
  frontend/src/ComponentsBoard/BoardHeader/index.css
  frontend/src/ComponentsBoard/BoardHeader/index.js
  frontend/src/ComponentsBoard/BoardPage/index.css
  frontend/src/ComponentsBoard/BoardPage/index.js
  frontend/src/ComponentsBoard/Comment/index.css
  frontend/src/ComponentsBoard/Comment/index.js
  frontend/src/ComponentsBoard/MainPage/index.css
  frontend/src/ComponentsBoard/MainPage/index.js
  frontend/src/ComponentsBoard/index.js
  frontend/src/routes/index.js
Labels: enhancement

#135 #134 - 공통적으로 사용되는 컴포넌트 폴더 분리
  frontend/src/ComponentsUsers/Footer/css.css
  frontend/src/ComponentsUsers/Footer/index.js
  frontend/src/ComponentsUsers/Header/css.css
  frontend/src/ComponentsUsers/Header/index.js
  frontend/src/ComponentsUsers/Login/index.js
  frontend/src/ComponentsUsers/MyPage/ArticleList.js
  frontend/src/ComponentsUsers/MyPage/CommentList.js
  frontend/src/ComponentsUsers/MyPage/Info.js
  frontend/src/ComponentsUsers/MyPage/Profile.js
  frontend/src/ComponentsUsers/MyPage/index.js
  frontend/src/ComponentsUsers/SignUp/index.js
  frontend/src/ComponentsUsers/index.js
  frontend/src/ComponentsUtils/Card/css.css
  frontend/src/ComponentsUtils/Card/index.js
  frontend/src/ComponentsUtils/List/List.js
  frontend/src/ComponentsUtils/List/ListCom.js
  frontend/src/ComponentsUtils/List/PaginationBar.js
  frontend/src/ComponentsUtils/List/SearchInput.js
  frontend/src/ComponentsUtils/RNW/css.css
  frontend/src/ComponentsUtils/RNW/index.js
  frontend/src/ComponentsUtils/Sheet/css.css
  frontend/src/ComponentsUtils/Sheet/index.js
  frontend/src/ComponentsUtils/Toast/css.css
  frontend/src/ComponentsUtils/Toast/index.js
  frontend/src/ComponentsUtils/index.js
  frontend/src/routes/index.js
Labels: documentation, enhancement

#139 #138 - 게시판 관리 대시보드 페이지 생성
  back_end/src/main/java/com/chirp/community/model/BoardDto.java
  back_end/src/main/java/com/chirp/community/model/response/BoardReadResponse.java
  back_end/src/main/java/com/chirp/community/repository/BoardRepository.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/ComponentsUsers/BoardDashBoard/BoardList.js
  frontend/src/ComponentsUsers/BoardDashBoard/ButtonSet.js
  frontend/src/ComponentsUsers/BoardDashBoard/Config.js
  frontend/src/ComponentsUsers/BoardDashBoard/css.css
  frontend/src/ComponentsUsers/BoardDashBoard/index.js
  frontend/src/ComponentsUsers/MyPage/ArticleList.js
  frontend/src/ComponentsUsers/MyPage/CommentList.js
  frontend/src/ComponentsUsers/index.js
  frontend/src/ComponentsUtils/List/ListCom.js
  frontend/src/ComponentsUtils/List/PaginationBar.js
  frontend/src/ComponentsUtils/List/SearchInput.js
  frontend/src/ComponentsUtils/TitleWithIcon.js
  frontend/src/ComponentsUtils/index.js
  frontend/src/routes/index.js
  frontend/src/utils/index.js
Labels: documentation, enhancement

#142 #138 - 관리자 대시보드
  back_end/src/main/java/com/chirp/community/configuration/AuthenticationConfig.java
  back_end/src/main/resources/data.sql
  frontend/src/ComponentsUsers/BoardDashBoard/BoardList.js
  frontend/src/ComponentsUsers/BoardDashBoard/Config.js
Labels: documentation, enhancement

#143 Feature/#136 유저 공통 페이지 구현
  frontend/src/ComponentsUsers/UserPage/Info.js
  frontend/src/utils/index.js
Labels: documentation, enhancement

#153 #152 - data.sql 중 유저 칼럼 email의 유일성 훼손 버그 수정
  back_end/src/main/resources/data.sql
Labels: bug

#151 #150 - 유저 정보 업데이트 시 최고 관리자 인식 불가 버그 수정
  back_end/src/main/java/com/chirp/community/service/SiteUserServiceImpl.java
  back_end/src/main/java/com/chirp/community/utils/AccessAuthorizer.java
Labels: bug

#145 #144 - Redux 영속성 부여
  frontend/src/ComponentsUsers/BoardDashBoard/BoardList.js
  frontend/src/store/actions/AuthAction.js
  frontend/src/store/index.js
  frontend/src/store/util.js
Labels: bug

#149 #148 - JS 로그 가독성 향상
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/index.js
Labels: documentation, enhancement

#147 #146 - 로그아웃 컴포넌트 추출
  frontend/src/Header/BoardAdminAuth.js
  frontend/src/Header/LogOut.js
  frontend/src/Header/PrimeAdminAuth.js
  frontend/src/Header/UserAuth.js
  frontend/src/store/reducers/AuthReducer.js
Labels: documentation, enhancement

#156 Feature/#118 게시글작성페이지 기본구현
  .gitignore
  frontend/src/ComponentsBoard/ArticleCreatePage/index.css
  frontend/src/ComponentsBoard/ArticleCreatePage/indxe.js
  frontend/src/ComponentsBoard/ArticleHeader/index.js
  frontend/src/ComponentsBoard/ArticlePage/index.js
  frontend/src/ComponentsBoard/BoardHeader/index.js
  frontend/src/ComponentsBoard/BoardPage/index.js
  frontend/src/ComponentsBoard/MainPage/index.js
  frontend/src/ComponentsBoard/index.js
  frontend/src/Header/index.js
  frontend/src/routes/index.js
Labels: enhancement

#158 Feature/#155 이메일을 이용한 계정 보안 강화
  back_end/build.gradle
  back_end/src/main/java/com/chirp/community/configuration/AuthenticationConfig.java
  back_end/src/main/java/com/chirp/community/configuration/RedisConfig.java
  back_end/src/main/java/com/chirp/community/controller/AuthController.java
  back_end/src/main/java/com/chirp/community/entity/VerificationCode.java
  back_end/src/main/java/com/chirp/community/model/EmailDto.java
  back_end/src/main/java/com/chirp/community/model/SiteUserDto.java
  back_end/src/main/java/com/chirp/community/model/response/SiteUserReadResponse.java
  back_end/src/main/java/com/chirp/community/properties/RedisProperties.java
  back_end/src/main/java/com/chirp/community/properties/VerificationCodeProperties.java
  back_end/src/main/java/com/chirp/community/repository/EmailRepository.java
  back_end/src/main/java/com/chirp/community/repository/EmailRepositoryImpl.java
  back_end/src/main/java/com/chirp/community/repository/VerificationCodeRepository.java
  back_end/src/main/java/com/chirp/community/repository/VerificationCodeRepositoryImpl.java
  back_end/src/main/java/com/chirp/community/service/AuthService.java
  back_end/src/main/java/com/chirp/community/service/AuthServiceImpl.java
  back_end/src/main/java/com/chirp/community/service/EmailService.java
  back_end/src/main/java/com/chirp/community/service/EmailServiceImpl.java
  back_end/src/main/java/com/chirp/community/service/SiteUserServiceImpl.java
  back_end/src/main/java/com/chirp/community/service/VerificationCodeService.java
  back_end/src/main/java/com/chirp/community/service/VerificationCodeServiceImpl.java
  back_end/src/main/java/com/chirp/community/type/RoleType.java
  back_end/src/main/java/com/chirp/community/utils/EmailContentUtils.java
  back_end/src/main/java/com/chirp/community/utils/VerificationCodeUtils.java
  back_end/src/main/resources/application-email.yml
  back_end/src/main/resources/application-redis.yml
  back_end/src/main/resources/application.yml
  back_end/src/main/resources/data.sql
  frontend/package-lock.json
  frontend/package.json
  frontend/src/ComponentsUsers/EmailVerification/MustBeVerifiedCom.js
  frontend/src/ComponentsUsers/EmailVerification/Timer.js
  frontend/src/ComponentsUsers/EmailVerification/VerifiedCom.js
  frontend/src/ComponentsUsers/EmailVerification/css.css
  frontend/src/ComponentsUsers/EmailVerification/index.js
  frontend/src/ComponentsUsers/MyPage/Info.js
  frontend/src/ComponentsUsers/MyPage/index.js
  frontend/src/ComponentsUsers/UserPage/Info.js
  frontend/src/ComponentsUtils/AuthorizedCom/SiteUserVerifedWithEmail.js
  frontend/src/Header/UserVerifiedAuth.js
  frontend/src/Header/index.js
Labels: documentation, enhancement

#159 #119-댓글 백엔드 구현
  back_end/src/main/java/com/chirp/community/controller/ArticleCommentController.java
  back_end/src/main/java/com/chirp/community/entity/ArticleComment.java
  back_end/src/main/java/com/chirp/community/model/ArticleCommentDto.java
  back_end/src/main/java/com/chirp/community/model/request/ArticleCommentCreateRequest.java
  back_end/src/main/java/com/chirp/community/model/response/ArticleCommentReadResponse.java
  back_end/src/main/java/com/chirp/community/repository/ArticleCommentRepository.java
  back_end/src/main/java/com/chirp/community/service/ArticleCommentService.java
  back_end/src/main/java/com/chirp/community/service/ArticleCommentServiceImpl.java
Labels: enhancement

#161 Feature/#160 각종 버그 수정
  back_end/.gitignore
  back_end/src/main/java/com/chirp/community/configuration/AuthenticationConfig.java
  back_end/src/main/java/com/chirp/community/controller/AuthController.java
  back_end/src/main/java/com/chirp/community/controller/SiteUserController.java
  back_end/src/main/java/com/chirp/community/model/request/SiteUserUpdateRequest.java
  back_end/src/main/java/com/chirp/community/service/ArticleServiceImpl.java
  back_end/src/main/java/com/chirp/community/service/AuthService.java
  back_end/src/main/java/com/chirp/community/service/AuthServiceImpl.java
  back_end/src/main/java/com/chirp/community/service/SiteUserService.java
  back_end/src/main/java/com/chirp/community/service/SiteUserServiceImpl.java
  frontend/src/ComponentsUsers/EmailVerification/MustBeVerifiedCom.js
  frontend/src/ComponentsUsers/EmailVerification/index.js
  frontend/src/ComponentsUsers/Login/index.js
  frontend/src/ComponentsUsers/UserPage/Info.js
Labels: bug

#163 #162 - XXXDto.fromEntity에 의한 Lazy Loading 버그
  back_end/src/main/java/com/chirp/community/controller/BoardController.java
  back_end/src/main/java/com/chirp/community/controller/SiteUserController.java
  back_end/src/main/java/com/chirp/community/model/ArticleDto.java
  back_end/src/main/java/com/chirp/community/model/response/ArticleReadBoardPageRowResponse.java
  back_end/src/main/java/com/chirp/community/model/response/ArticleReadMyPageRowResponse.java
  back_end/src/main/java/com/chirp/community/repository/ArticleRepository.java
  back_end/src/main/java/com/chirp/community/service/ArticleServiceImpl.java
  frontend/src/ComponentsBoard/BoardPage/index.js
  frontend/src/ComponentsUsers/UserPageCom/ArticleList.js
  frontend/src/ComponentsUsers/UserPageCom/CommentList.js
Labels: bug

#165 #164 - MyPage 댓글 목록 로드 기능 구현
  back_end/src/main/java/com/chirp/community/controller/ArticleCommentController.java
  back_end/src/main/java/com/chirp/community/model/ArticleCommentDto.java
  back_end/src/main/java/com/chirp/community/repository/ArticleCommentRepository.java
  back_end/src/main/java/com/chirp/community/service/ArticleCommentService.java
  back_end/src/main/java/com/chirp/community/service/ArticleCommentServiceImpl.java
  back_end/src/main/resources/data.sql
  frontend/src/ComponentsUsers/UserPageCom/ArticleList.js
  frontend/src/ComponentsUsers/UserPageCom/CommentList.js
Labels: documentation, enhancement

#167 Feature/#120 댓글 프론트 기본구현
  back_end/src/main/java/com/chirp/community/controller/ArticleCommentController.java
  back_end/src/main/java/com/chirp/community/model/ArticleCommentDto.java
  back_end/src/main/java/com/chirp/community/model/request/ArticleCommentUpdateRequest.java
  back_end/src/main/resources/data.sql
  frontend/src/ComponentsBoard/ArticleCreatePage/indxe.js
  frontend/src/ComponentsBoard/ArticlePage/index.js
  frontend/src/ComponentsBoard/BoardHeader/index.js
  frontend/src/ComponentsBoard/BoardPage/index.js
  frontend/src/ComponentsBoard/Comment/index.css
  frontend/src/ComponentsBoard/Comment/index.js
Labels: enhancement

#170 #169 - 개인 정보 수정 시 이메일 변경에도 이메일 인증으로 뜨는 버그 수정
  back_end/src/main/java/com/chirp/community/service/SiteUserServiceImpl.java
  frontend/src/store/reducers/AuthReducer.js
Labels: bug

#172 #171 - 댓글 추천 컴포넌트 생성
  back_end/src/main/java/com/chirp/community/controller/ArticleCommentController.java
  back_end/src/main/java/com/chirp/community/entity/ArticleCommentLikes.java
  back_end/src/main/java/com/chirp/community/repository/ArticleCommentLikesRepository.java
  back_end/src/main/java/com/chirp/community/service/ArticleCommentLikesService.java
  back_end/src/main/java/com/chirp/community/service/ArticleCommentLikesServiceImpl.java
  back_end/src/main/resources/data.sql
  back_end/src/main/resources/mysql_schema.sql
  frontend/src/ComponentsBoard/Comment/index.js
  frontend/src/ComponentsUtils/LikesComSm/BtnDisLikes.js
  frontend/src/ComponentsUtils/LikesComSm/BtnLikes.js
  frontend/src/ComponentsUtils/LikesComSm/Label.js
  frontend/src/ComponentsUtils/LikesComSm/css.css
  frontend/src/ComponentsUtils/LikesComSm/index.js
  frontend/src/ComponentsUtils/index.js
Labels: documentation, enhancement
